name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - AlexHaible
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the addon are you running?
      placeholder: "1.0.0"
    validations:
      required: true
  - type: dropdown
    id: game-version
    attributes:
      label: What game version are you seeing the problem on?
      multiple: true
      options:
        - Retail
        - Retail Beta
        - Retail PTR
        - Classic Era
        - Classic Era PTR
        - Cataclysm Classic
        - Cataclysm Classic PTR
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: lua
